- file:
    state: directory
    path: "{{ compute_schedule_dir }}"
    mode: 0700
    owner: "{{ uid }}"
    group: "{{ gid }}"
- template:
    src: compose.yaml.j2
    dest: "{{ compute_schedule_dir }}/compose.yaml"
    owner: "{{ uid }}"
    group: "{{ gid }}"
- include_role:
    name: use-docker-for-schedule
  when: compute_docker is defined and compute_docker
- file:
    state: directory
    path: "{{ compute_schedule_dir }}/config"
    owner: "{{ uid }}"
    group: "{{ gid }}"
- copy:
    src: /notebooks/notebook/vcp_config/vcp_config.yml
    dest: "{{ compute_schedule_dir }}/config/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
- copy:
    src: /notebooks/notebook/vcp_config/vcp_flavor.yml
    dest: "{{ compute_schedule_dir }}/config/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
- file:
    state: directory
    path: "{{ compute_schedule_dir }}/secrets"
    mode: 0700
    owner: "{{ uid }}"
    group: "{{ gid }}"
- copy:
    dest: "{{ compute_schedule_dir }}/secrets/SSH_PRIVATE_KEY"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: 0600
    content: |
        {{ lookup('file', ssh_private_key_path) }}
- copy:
    dest: "{{ compute_schedule_dir }}/secrets/VCC_ACCESS_TOKEN"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: 0600
    content: |-
        {{ vcc_access_token }}
- command:
    cmd: docker compose pull
    chdir: "{{ compute_schedule_dir }}"
