- name: Install Docker Engine
  block:
    - dnf:
        name: dnf-plugins-core
        update_cache: yes
        state: present
    - command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        creates: /etc/yum.repos.d/docker-ce.repo
    - dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - fuse-overlayfs
        update_cache: yes
        state: present
- name: Configure Docker daemon
  copy:
    content: |
      {
        "storage-driver": "fuse-overlayfs"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
- name: Start and enable Docker Engine
  systemd:
    name: docker
    state: started
    enabled: yes
