#!/bin/bash

init_moodle() {
    php /var/www/html/admin/cli/install.php \
        --lang=ja \
        --non-interactive \
        --wwwroot=${MOODLE_URL} \
        --dataroot=${MOODLE_DATAROOT} \
        --dbtype=${MOODLE_DBTYPE} \
        --dbhost=${DB_HOSTNAME} \
        --dbpass=${DB_PASSWORD} \
        --dbname=${DB_DATABASE} \
        --dbuser=${DB_USER} \
        --fullname="${MOODLE_FULLNAME:-Example University Moodle Demo}" \
        --shortname="${MOODLE_SHORTNAME:-demo moodle}" \
        --adminuser=${MOODLE_ADMIN} \
        --adminpass=${MOODLE_ADMIN_PASSWORD} \
        --agree-license 1>&2

    : ${MOODLE_REVERSEPROXY:=false}
    if [ ${MOODLE_REVERSEPROXY,,} = "true" ]; then
      sed -i -r -e "/^require_once/s#^#\$CFG->reverseproxy = true;\n#" \
        /var/www/html/config.php
      if [[ ${MOODLE_URL} =~ ^https:// ]]; then
        sed -i -r -e "/^require_once/s#^#\$CFG->sslproxy = true;\n#" \
          /var/www/html/config.php
      fi
    fi
    if [ -n "$TZ" ]; then
        sed -i -r -e "/^require_once/s#^#\$CFG->timezone = '$TZ';\n#" \
          /var/www/html/config.php
    fi

    declare -A params

    params=(
      ["pathtophp"]="'/usr/bin/php'"
      ["pathtodu"]="'/usr/bin/du'"
      ["aspellpath"]="'/usr/bin/aspell'"
      ["pathtodot"]="'/usr/bin/dot'"
      ["pathtogs"]="'/usr/bin/gs'"
      ["pathtopython"]="'/usr/bin/python'"
      ["preventexecpath"]="true"
    )

    for param in ${!params[@]}; do
      sed -i -r -e "/require_once/s#^#\$CFG->${param} = ${params[$param]};\n#" \
        /var/www/html/config.php
    done

    chmod +r /var/www/html/config.php
    mkdir -p /var/data/tmp
    cp /var/www/html/config.php /var/data/tmp
}

set_config() {
    key="$1"
    value="$2"
    php_escaped_value="$(php -r 'var_export($argv[1]);' "$value")"
    sed_escaped_value="$(echo "$php_escaped_value" | sed 's/[\/&]/\\&/g')"
    sed -i "s/\$CFG->$key[ ]*=[ ]*.\+/\$CFG->$key = $sed_escaped_value;/" /var/www/html/config.php
}

update_config_php() {
    cp /var/www/html/config.php /var/www/html/config.php.bak
    set_config 'wwwroot' "${MOODLE_URL}"
    set_config 'dataroot' "${MOODLE_DATAROOT}"
    set_config 'dbhost' "${DB_HOSTNAME}"
    set_config 'dbname' "${DB_DATABASE}"
    set_config 'dbuser' "${DB_USER}"
    set_config 'dbpass' "${DB_PASSWORD}"
}

if [ $# -gt 0 -a "X$1" = 'X--no-install' ]; then
  rm -rf /var/run/httpd/*
  exec /usr/sbin/httpd -DFOREGROUND
fi

if [ ! -f /var/www/html/config.php ]; then
    init_moodle
else
    update_config_php
fi
update-ca-trust extract
cat /var/www/html/config.php

rm -rf /var/run/httpd/*
exec /usr/sbin/httpd -DFOREGROUND
