{
 "title": "Node Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(machine_cpu_cores, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average",
   "type": "graph",
   "description": "0-150 (150 threads)",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(container_cpu_load_average_10s{id=\"/\",instance=~\"(${instance:pipe}).*\"}) by (instance) / 1000, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "0 - 15000% (150 threads)",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(container_cpu_system_seconds_total{id=\"/\", instance=~\"(${instance:pipe}).*\"}[1m]) * 100) by (instance), \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:system"
    },
    {
     "expr": "label_replace(sum(irate(container_cpu_user_seconds_total{id=\"/\", instance=~\"(${instance:pipe}).*\"}[1m]) * 100) by (instance), \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:user"
    }
   ]
  },
  {
   "title": "Memory / Swap Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(container_memory_rss{id=\"/\",instance=~\"(${instance:pipe}).+\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:rss"
    },
    {
     "expr": "label_replace(container_memory_mapped_file{id=\"/\",instance=~\"(${instance:pipe}).+\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:mapped_file"
    },
    {
     "expr": "label_replace(container_memory_cache{id=\"/\",instance=~\"(${instance:pipe}).+\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:cache"
    },
    {
     "expr": "label_replace(container_memory_swap{id=\"/\",instance=~\"(${instance:pipe}).+\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:swap"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(container_fs_reads_bytes_total{instance=~\"(${instance:pipe}).*\"}[1m])) by (instance), \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "label_replace(sum(irate(container_fs_writes_bytes_total{instance=~\"(${instance:pipe}).*\"}[1m])) by (instance), \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:written"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(container_fs_usage_bytes{instance=~\"(${instance:pipe}).*\",device=~\"/dev/.*\",id=\"/\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:{{device}}:used"
    },
    {
     "expr": "label_replace(container_fs_limit_bytes{instance=~\"(${instance:pipe}).*\",device=~\"/dev/.*\",id=\"/\"} - container_fs_usage_bytes{instance=~\"(${instance:pipe}).*\",device=~\"/dev/.*\",id=\"/\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):[0-9]+\")",
     "legendFormat": "{{instance}}:{{device}}:free"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "sum metrics of all containers/cgroups",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total[1m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}