diff --git a/Dockerfile b/Dockerfile
index 8992075..bb794d3 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,6 @@
 FROM jupyter/scipy-notebook:latest
-MAINTAINER https://github.com/NII-cloud-operation
+
+LABEL maintainer https://github.com/NII-cloud-operation
 
 USER root
 # Install tools and fonts
@@ -25,23 +26,32 @@ RUN apt-get update && apt-get install -yq --no-install-recommends \
     rm -rf /var/lib/apt/lists/*
 
 # Copy config files
-ADD conf /tmp/
-RUN mkdir -p $CONDA_DIR/etc/jupyter && \
+COPY conf /tmp/
+RUN mkdir -p "$CONDA_DIR/etc/jupyter" && \
     cp -f /tmp/jupyter_notebook_config.py \
-       $CONDA_DIR/etc/jupyter/jupyter_notebook_config.py
+       "$CONDA_DIR/etc/jupyter/jupyter_notebook_config.py"
 
 SHELL ["/bin/bash", "-c"]
 
 ### ansible
 RUN apt-get update && \
-    apt-get -y install sshpass openssl ipmitool libssl-dev libffi-dev && \
+    apt-get -y install --no-install-recommends \
+      sshpass openssl ipmitool libssl-dev libffi-dev && \
     apt-get clean && rm -rf /var/lib/apt/lists/* && \
     pip --no-cache-dir install requests paramiko ansible
 
 ### Utilities
-RUN apt-get update && apt-get install -y virtinst dnsutils zip tree jq rsync iputils-ping && \
-    apt-get clean && rm -rf /var/lib/apt/lists/* && \
-    pip --no-cache-dir install netaddr pyapi-gitlab runipy papermill \
+RUN apt-get update \
+  && apt-get install -y --no-install-recommends \
+       virtinst \
+       dnsutils \
+       zip \
+       tree \
+       jq \
+       rsync \
+       iputils-ping \
+  && apt-get clean && rm -rf /var/lib/apt/lists/* \
+  && pip --no-cache-dir install netaddr pyapi-gitlab runipy papermill \
                 pysnmp pysnmp-mibs
 
 ### Add files
@@ -93,36 +103,39 @@ RUN jupyter contrib nbextension install --sys-prefix && \
     jupyter kernelspec install /tmp/kernels/bash-wrapper --sys-prefix && \
     jupyter wrapper-kernelspec install /tmp/wrapper-kernels/python3 --sys-prefix && \
     jupyter wrapper-kernelspec install /tmp/wrapper-kernels/bash --sys-prefix && \
-    fix-permissions /home/$NB_USER
+    fix-permissions "/home/$NB_USER"
 
 ### nbconfig
-RUN mkdir -p $CONDA_DIR/etc/jupyter/nbconfig/notebook.d && \
-    cp /tmp/nbextension-config.json $CONDA_DIR/etc/jupyter/nbconfig/notebook.d/nbextension-config.json
+RUN mkdir -p "$CONDA_DIR/etc/jupyter/nbconfig/notebook.d" && \
+    cp /tmp/nbextension-config.json "$CONDA_DIR/etc/jupyter/nbconfig/notebook.d/nbextension-config.json"
 
 ### notebooks dir
-ADD sample-notebooks /home/$NB_USER
-RUN fix-permissions /home/$NB_USER
+COPY sample-notebooks /home/$NB_USER
+RUN fix-permissions "/home/$NB_USER"
 
 ### Bash Strict Mode
 RUN cp /tmp/bash_env /etc/bash_env
 
 ### Theme for jupyter
 RUN CUSTOM_DIR=$(python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())')/notebook/static/custom && \
-    cat /tmp/custom.css >> $CUSTOM_DIR/custom.css && \
-    cp /tmp/logo.png $CUSTOM_DIR/logo.png && \
-    mkdir -p $CUSTOM_DIR/codemirror/addon/merge/ && \
-    curl -fL https://raw.githubusercontent.com/cytoscape/cytoscape.js/master/dist/cytoscape.min.js > $CUSTOM_DIR/cytoscape.min.js && \
-    curl -fL https://raw.githubusercontent.com/iVis-at-Bilkent/cytoscape.js-view-utilities/master/cytoscape-view-utilities.js > $CUSTOM_DIR/cytoscape-view-utilities.js && \
-    curl -fL https://raw.githubusercontent.com/NII-cloud-operation/Jupyter-LC_notebook_diff/master/html/jupyter-notebook-diff.js > $CUSTOM_DIR/jupyter-notebook-diff.js && \
-    curl -fL https://raw.githubusercontent.com/NII-cloud-operation/Jupyter-LC_notebook_diff/master/html/jupyter-notebook-diff.css > $CUSTOM_DIR/jupyter-notebook-diff.css && \
-    curl -fL https://cdnjs.cloudflare.com/ajax/libs/diff_match_patch/20121119/diff_match_patch.js > $CUSTOM_DIR/diff_match_patch.js && \
-    curl -fL https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/addon/merge/merge.js > $CUSTOM_DIR/codemirror/addon/merge/merge.js && \
-    curl -fL https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/addon/merge/merge.min.css > $CUSTOM_DIR/merge.min.css
+    cat /tmp/custom.css >> "$CUSTOM_DIR/custom.css" && \
+    cp /tmp/logo.png "$CUSTOM_DIR/logo.png" && \
+    mkdir -p "$CUSTOM_DIR/codemirror/addon/merge/" && \
+    curl -fL https://raw.githubusercontent.com/cytoscape/cytoscape.js/master/dist/cytoscape.min.js > "$CUSTOM_DIR/cytoscape.min.js" && \
+    curl -fL https://raw.githubusercontent.com/iVis-at-Bilkent/cytoscape.js-view-utilities/master/cytoscape-view-utilities.js > "$CUSTOM_DIR/cytoscape-view-utilities.js" && \
+    curl -fL https://raw.githubusercontent.com/NII-cloud-operation/Jupyter-LC_notebook_diff/master/html/jupyter-notebook-diff.js > "$CUSTOM_DIR/jupyter-notebook-diff.js" && \
+    curl -fL https://raw.githubusercontent.com/NII-cloud-operation/Jupyter-LC_notebook_diff/master/html/jupyter-notebook-diff.css > "$CUSTOM_DIR/jupyter-notebook-diff.css" && \
+    curl -fL https://cdnjs.cloudflare.com/ajax/libs/diff_match_patch/20121119/diff_match_patch.js > "$CUSTOM_DIR/diff_match_patch.js" && \
+    curl -fL https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/addon/merge/merge.js > "$CUSTOM_DIR/codemirror/addon/merge/merge.js" && \
+    curl -fL https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/addon/merge/merge.min.css > "$CUSTOM_DIR/merge.min.css"
+
+# enable lc_notebook_diff extension
+RUN jupyter nbextension enable --py lc_notebook_diff --sys-prefix
 
 ### Custom get_ipython().system() to control error propagation of shell commands
-RUN mkdir -p $CONDA_DIR/etc/ipython/startup/ && \
-    cp /tmp/ipython_config.py $CONDA_DIR/etc/ipython/ && \
-    cp /tmp/10-custom-get_ipython_system.py $CONDA_DIR/etc/ipython/startup/
+RUN mkdir -p "$CONDA_DIR/etc/ipython/startup/" && \
+    cp /tmp/ipython_config.py "$CONDA_DIR/etc/ipython/" && \
+    cp /tmp/10-custom-get_ipython_system.py "$CONDA_DIR/etc/ipython/startup/"
 
 ### Add run-hooks
 RUN mkdir -p /usr/local/bin/before-notebook.d && \
