- hosts: all
  become: true
  roles:
    - role: docker
      when: not (install_via_schedule | default(false))
    - role: nvidia-container-toolkit
      when: not (install_via_schedule | default(false)) and feature_use_gpu
    - role: use-docker-for-schedule
      when: install_via_schedule | default(false)
