- copy:
    src: compose.default-nodes.yaml
    dest: "{{ worker_schedule_dir }}/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
- command:
    cmd: docker compose -f compose.yaml -f compose.default-nodes.yaml up
    chdir: "{{ worker_schedule_dir }}"
