- file:
    path: /srv/moodle/setup
    state: directory
    owner: "{{ansible_ssh_user}}"
  become: true
- template:
    src: compose.setup-ssl.yaml.j2
    dest: /srv/moodle/setup/compose.setup-ssl.yaml
- command:
    chdir: /srv/moodle
    cmd: docker compose -f setup/compose.setup-ssl.yaml pull
- command:
    chdir: /srv/moodle
    cmd: docker compose -f setup/compose.setup-ssl.yaml up -d
- file:
    path: /srv/moodle/httpd
    state: directory
    owner: "{{ansible_ssh_user}}"
  become: true
- file:
    path: /srv/moodle/httpd/conf
    state: directory
    owner: "{{ansible_ssh_user}}"
  become: true
- shell:
    chdir: /srv/moodle
    cmd: docker cp -a setup-httpd:/etc/httpd httpd/conf || true
  become: true
- command:
    chdir: /srv/moodle
    cmd: docker compose -f setup/compose.setup-ssl.yaml down
