#!/bin/bash

: ${ENABLE_HTTPD:=true}

init_moodle() {
    php /var/www/moodle/admin/cli/install.php \
        --lang=ja \
        --non-interactive \
        --wwwroot=${MOODLE_URL} \
        --dataroot=${MOODLE_DATAROOT} \
        --dbtype=${MOODLE_DBTYPE} \
        --dbhost=${DB_HOSTNAME} \
        --dbpass=${DB_PASSWORD} \
        --dbname=${DB_DATABASE} \
        --dbuser=${DB_USER} \
        --fullname="${MOODLE_FULLNAME:-Example University Moodle Demo}" \
        --shortname="${MOODLE_SHORTNAME:-demo moodle}" \
        --adminuser=${MOODLE_ADMIN} \
        --adminpass=${MOODLE_ADMIN_PASSWORD} \
        --agree-license 1>&2

    if [[ ${MOODLE_URL} =~ ^https:// ]]; then
      sed -i -r -e "/^require_once/s#^#\$CFG->sslproxy = true;\n#" \
        /var/www/moodle/config.php
    fi
    if [ -n "$TZ" ]; then
        sed -i -r -e "/^require_once/s#^#\$CFG->timezone = '$TZ';\n#" \
          /var/www/moodle/config.php
    fi

    declare -A params

    params=(
      ["pathtophp"]="'/usr/bin/php'"
      ["pathtodu"]="'/usr/bin/du'"
      ["aspellpath"]="'/usr/bin/aspell'"
      ["pathtodot"]="'/usr/bin/dot'"
      ["pathtogs"]="'/usr/bin/gs'"
      ["pathtopython"]="'/usr/bin/python3'"
      ["preventexecpath"]="true"
    )

    for param in ${!params[@]}; do
      sed -i -r -e "/require_once/s#^#\$CFG->${param} = ${params[$param]};\n#" \
        /var/www/moodle/config.php
    done

    chmod +r /var/www/moodle/config.php
    mkdir -p /var/data/tmp
    cp /var/www/moodle/config.php /var/data/tmp
}

set_config() {
    key="$1"
    value="$2"
    php_escaped_value="$(php -r 'var_export($argv[1]);' "$value")"
    sed_escaped_value="$(echo "$php_escaped_value" | sed 's/[\/&]/\\&/g')"
    sed -i "s/\$CFG->$key[ ]*=[ ]*.\+/\$CFG->$key = $sed_escaped_value;/" /var/www/moodle/config.php
}

update_config_php() {
    cp /var/www/moodle/config.php /var/www/moodle/config.php.bak
    set_config 'wwwroot' "${MOODLE_URL}"
    set_config 'dataroot' "${MOODLE_DATAROOT}"
    set_config 'dbhost' "${DB_HOSTNAME}"
    set_config 'dbname' "${DB_DATABASE}"
    set_config 'dbuser' "${DB_USER}"
    set_config 'dbpass' "${DB_PASSWORD}"
}

setup_secrets() {
    if [ -f /run/secrets/MOODLE_ADMIN_PASSWORD ]; then
      MOODLE_ADMIN_PASSWORD=$(cat /run/secrets/MOODLE_ADMIN_PASSWORD)
    fi
    if [ -f /run/secrets/MOODLE_ADMIN ]; then
      MOODLE_ADMIN=$(cat /run/secrets/MOODLE_ADMIN)
    fi
    if [ -f /run/secrets/DB_PASSWORD ]; then
      DB_PASSWORD=$(cat /run/secrets/DB_PASSWORD)
    fi
    if [ -f /run/secrets/DB_USER ]; then
      DB_USER=$(cat /run/secrets/DB_USER)
    fi
    if [ -f /run/secrets/DB_DATABASE ]; then
      DB_DATABASE=$(cat /run/secrets/DB_DATABASE)
    fi
}

if [ $# -gt 0 -a "X$1" = 'X--no-install' ]; then
  rm -rf /var/run/httpd/*
  exec /usr/sbin/httpd -DFOREGROUND
fi

setup_secrets
if [ ! -f /var/www/moodle/config.php ]; then
    init_moodle
else
    update_config_php
fi
update-ca-trust extract
cat /var/www/moodle/config.php

rm -rf /var/run/httpd/*
rm -rf /var/run/php-fpm/*
mkdir -p /var/run/php-fpm

if [ "${ENABLE_HTTPD,,}" = "true" ]; then
exec /usr/bin/supervisord -n
else
exec /usr/sbin/php-fpm -F
fi