{
 "title": "JupyterHub",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "# of User Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~'jupyter-.+'}) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "# of user containers"
    }
   ]
  },
  {
   "title": "Auth-proxy Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~'.+_auth-proxy'}[30s])) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~'.+_auth-proxy'}[30s])) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Total memory usages of User containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_com_docker_swarm_service_name=~'jupyter-.+'})",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_service_name=~'jupyter-.+'})",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(container_memory_swap{container_label_com_docker_swarm_service_name=~'jupyter-.+'})",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Total CPU usages of User containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~'jupyter-.+'}[30s])) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  }
 ]
}