{
 "title": "System Container Metircs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "stack",
    "query": "label_values(container_memory_usage_bytes,container_label_com_docker_swarm_service_name)"
   },
   { "name": "service", "query": "auth-proxy,jupyterhub,postgres" }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}[1m])) by(container_label_com_docker_swarm_service_name) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container Memory / Swap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:rss"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:cache"
    },
    {
     "expr": "sum(container_memory_swap{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:swap"
    }
   ]
  },
  {
   "title": "Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}[30s])) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:rx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}[30s])) by(container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:tx"
    }
   ]
  },
  {
   "title": "Container Filesystem I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}[1m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:writes"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{container_label_com_docker_swarm_service_name=~'(${stack:pipe})_(${service:pipe})'}[1m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}:reads"
    }
   ]
  }
 ]
}